#!/bin/sh
set -eu

OUT_DIR="${1:-./bpi-r4-validation-report}"
mkdir -p "$OUT_DIR"

capture() {
  name="$1"
  shift
  {
    echo "# $name"
    echo
    echo "## command"
    printf '```sh\n%s\n```\n\n' "$*"
    echo "## output"
    echo '```'
    "$@" 2>&1 || true
    echo '```'
  } > "$OUT_DIR/$name.md"
}

capture uname uname -a
capture cmdline cat /proc/cmdline
capture board_json cat /etc/board.json
capture block_info block info
capture mount mount
capture df_h df -h
capture dmesg_tail sh -c 'dmesg | tail -n 200'
capture logread_tail sh -c 'logread | tail -n 200'
capture fw_printenv sh -c 'fw_printenv 2>/dev/null || true'

if command -v lsblk >/dev/null 2>&1; then
  capture lsblk lsblk
fi

if [ -b /dev/mmcblk0 ] && command -v parted >/dev/null 2>&1; then
  capture mmcblk0_parted parted -s /dev/mmcblk0 print
fi

if [ -e /sys/class/block/mmcblk0/device/type ]; then
  capture mmcblk0_type cat /sys/class/block/mmcblk0/device/type
fi

if [ -e /etc/.sd-data-expanded ]; then
  capture sd_expand_marker ls -l /etc/.sd-data-expanded
fi

cat > "$OUT_DIR/README.md" <<'EOF'
# BPI-R4 Runtime Validation Capture

This directory was generated by `tools/collect_bpi_r4_runtime_report.sh` on a live
BPI-R4 device. Attach it to a test report together with:

- tested release tag / commit SHA
- boot medium (SD / eMMC / SPI-NAND)
- board RAM size
- bootloader version
- pass/fail notes for boot, storage, upgrade, and rollback
EOF

echo "Saved validation capture to $OUT_DIR"
